name: Publish to PyPI (Trusted Publishing)

on:
  release:
    types: [published]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: pytest --maxfail=1 --disable-warnings -q

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: |
          python -m pip install --upgrade pip build
          python -m build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
